---
title: "Soil Figure"
format: html
execute: 
  warning: false
  error: false
---

# Generate Ternary plot

```{r}
library(tidyverse)
library(ggtern)
library(janitor)
```


```{r}
soil_raw <- read_delim("data/DatosFisicoquimicos_Psylvestris.txt") |> 
  clean_names() |> 
  mutate(site = ifelse(site == "Snevada",  "S. Nevada", paste0("S. ", site)))
```


```{r}
cols_sites <- c(
  "S. Almijara" = "#02BFFF",
  "S. Baza" = "#05FF01",
  "S. Nevada" = "#FF00FF"
)

shape_condition <- c(
  "Symptomatic" = 24, 
  "Asymptomatic" = 21)
```


```{r}
soil_raw_mean <- soil_raw |> 
  mutate(site_code = str_replace_all(sample, "[:digit:]", "")) |> 
  group_by(site_code, site, condition) |> 
  summarise(across(c(sand, slime, clay), 
                   list(mean = ~mean(.), 
                        sd = ~sd(.), 
                        se = ~sd(.)/sqrt(length(.)))))

soil_means <- soil_raw_mean |> 
  dplyr::select(site_code,site,condition, sand = sand_mean, slime = slime_mean, clay = clay_mean)


plot_soil <- ggtern(data = soil_raw, 
       aes(x = sand, y = clay, z = slime)) +
  geom_crosshair_tern(data = soil_means, 
                      aes(color = site),
                      lty="dashed", size = .1) + 
  geom_point(size = 2.5, 
             aes(shape = condition, color = site, fill = site), 
             alpha = 0.5, stroke = .4) +
  geom_point(data = soil_means, 
             aes(shape = condition, fill = site), colour = "black", size = 4) + 
  labs(yarrow = "Clay (%)", 
                zarrow = "Slime (%)",
                xarrow = "Sand (%)") +
  theme_bw() +
  ggplot2::xlab("") +
  ggplot2::ylab("") +
  ggtern::zlab("") +
  scale_colour_manual(values = cols_sites, 
                      name = "Site",
                      guide = guide_legend(override.aes = list(fill = cols_sites))) +
  scale_fill_manual(values = cols_sites, 
                    name = "Site",
                    guide = guide_legend(override.aes = list(color = cols_sites))) +
  scale_shape_manual(values = shape_condition, name = "Condition") +
  guides(
    colour = "none",
    fill = guide_legend("Site", 
                        override.aes = list(color = cols_sites, size = 1.5)),
    shape = guide_legend(override.aes = list(color = "black", fill = "white", size = 1.5))) +
  theme_showarrows() +
  theme(
   # panel.grid = element_blank(),
    legend.position = c(0.15, 0.80),
    legend.background = element_blank(),
    legend.text = element_text(size = 10),
    legend.key.size = unit(.5, "cm"),
    axis.title = element_text(size = 12), 
    axis.text = element_text(size = 14, face = "bold")
    ) 

plot_soil 
```

```{r}
#| echo: false
ggsave(
  plot_soil, 
  file = "output/plot_soil.png",
  dpi = 300,
  width = 15, height = 15,
  units = "cm"
)
```

  
 